test('grabs output from config file', () => {})
test('generates types based on config file', () => {})
test('outputs types into consumer of packages node modules like prisma', () => {})
test('initializes a Concoct singlton singleton', () => {})
test('has methods exposed on singleton based on config structure', () => {})
